version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: next_password
      POSTGRES_USER: next_password_user
      POSTGRES_PASSWORD: password_123
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
